#!/usr/bin/env node
// fetch-fonts.mjs — one-shot self-host downloader.
// Pulls latin + latin-ext woff2 subsets for Fraunces (variable 400–600),
// Instrument Sans (400, 500), JetBrains Mono (400, 500) from Google Fonts
// and writes a local @font-face block to assets/css/fonts.css. Re-runnable.
//
// Why: keep zero-build static hosting, but avoid runtime Google Fonts CDN
// (privacy, perf, GDPR). Pinned versions in CSS = stable, cache-bustable.

import { writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __root = join(dirname(fileURLToPath(import.meta.url)), "..");
const UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";
const CSS_URL =
  "https://fonts.googleapis.com/css2" +
  "?family=Fraunces:opsz,wght@9..144,400..600" +
  "&family=Instrument+Sans:wght@400;500" +
  "&family=JetBrains+Mono:wght@400;500" +
  "&display=swap";

const LATIN_RANGES = new Set([
  // latin
  "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
  // latin-ext
  "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
]);

const slug = (s) => s.toLowerCase().replace(/\s+/g, "-");

async function main() {
  const cssResp = await fetch(CSS_URL, { headers: { "User-Agent": UA } });
  if (!cssResp.ok) throw new Error(`CSS fetch failed: ${cssResp.status}`);
  const css = await cssResp.text();

  const blocks = css.split(/(?=@font-face)/g).filter((b) => b.includes("@font-face"));
  const outBlocks = [];

  for (const block of blocks) {
    const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
    const weight = block.match(/font-weight:\s*([^;]+);/)?.[1].trim();
    const style = block.match(/font-style:\s*([^;]+);/)?.[1].trim() ?? "normal";
    const srcUrl = block.match(/src:\s*url\(([^)]+)\)/)?.[1];
    const range = block.match(/unicode-range:\s*([^;]+);/)?.[1].replace(/\s+/g, "");
    if (!family || !srcUrl || !range) continue;
    if (!LATIN_RANGES.has(range)) continue;

    const subset = range.startsWith("U+0000") ? "latin" : "latin-ext";
    const filename = `${slug(family)}-${weight.replace(/\s+/g, "")}-${subset}.woff2`;
    const localPath = `assets/fonts/${filename}`;

    const fontResp = await fetch(srcUrl, { headers: { "User-Agent": UA } });
    if (!fontResp.ok) throw new Error(`Font fetch failed (${srcUrl}): ${fontResp.status}`);
    const buf = Buffer.from(await fontResp.arrayBuffer());
    await mkdir(join(__root, "assets/fonts"), { recursive: true });
    await writeFile(join(__root, localPath), buf);
    console.log(`  ↳ ${localPath} (${(buf.length / 1024).toFixed(1)} KB)`);

    outBlocks.push(
      `@font-face {\n` +
      `  font-family: '${family}';\n` +
      `  font-style: ${style};\n` +
      `  font-weight: ${weight};\n` +
      `  font-display: swap;\n` +
      `  src: url('../fonts/${filename}') format('woff2');\n` +
      `  unicode-range: ${range.replace(/,/g, ", ")};\n` +
      `}`
    );
  }

  const header =
    "/* fonts.css — self-hosted woff2 subsets generated by tools/fetch-fonts.mjs.\n" +
    "   Do not edit by hand; re-run the script to refresh. */\n\n";
  await writeFile(join(__root, "assets/css/fonts.css"), header + outBlocks.join("\n\n") + "\n");
  console.log(`\nWrote assets/css/fonts.css with ${outBlocks.length} @font-face rules.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
